<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sasd.Pims.Application\Sasd.Pims.Application.csproj" />
    <ProjectReference Include="..\Sasd.Pims.Domain\Sasd.Pims.Domain.csproj" />
  </ItemGroup>

</Project>
