<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sasd.Pims.Application\Sasd.Pims.Application.csproj" />
    <ProjectReference Include="..\Sasd.Pims.Domain\Sasd.Pims.Domain.csproj" />
  </ItemGroup>

</Project>
