namespace Sasd.Pims.WinForms;

partial class Form1
{
    /// <summary>
    /// Container used by the Windows Forms designer for components that
    /// require deterministic disposal together with the form.
    /// </summary>
    /// <remarks>
    /// This field follows the pattern generated by the Windows Forms
    /// designer. Designer files are treated as generated code, so nullable
    /// annotations such as <c>IContainer?</c> are intentionally avoided here.
    /// </remarks>
    private System.ComponentModel.IContainer components = null;

    /// <summary>
    /// Releases the resources used by the form.
    /// </summary>
    /// <param name="disposing">
    /// <see langword="true"/> to dispose managed resources owned by the form;
    /// otherwise, <see langword="false"/>.
    /// </param>
    protected override void Dispose(bool disposing)
    {
        // Components created by the Windows Forms designer are registered
        // in this container and must be disposed together with the form.
        if (disposing)
        {
            components?.Dispose();
        }

        base.Dispose(disposing);
    }

    #region Windows Form Designer generated code

    /// <summary>
    /// Initializes controls and designer-managed form properties.
    /// </summary>
    /// <remarks>
    /// Visual Studio may regenerate this method when the form is edited
    /// with the Windows Forms designer.
    /// </remarks>
    private void InitializeComponent()
    {
        SuspendLayout();

        AutoScaleDimensions = new SizeF(7F, 15F);
        AutoScaleMode = AutoScaleMode.Font;
        ClientSize = new Size(800, 450);
        Name = "Form1";
        Text = "SASD PIMS";

        ResumeLayout(false);
    }

    #endregion
}
